<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ProductCatalog.Models\ProductCatalog.Models.csproj" />
      <ProjectReference Include="..\ProductCatalog.Repositories\ProductCatalog.Repositories.csproj" />
    </ItemGroup>

</Project>
